version: "2"

run:
  tests: false

linters:
  default: standard
  enable:
    - bodyclose
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godot
    - nilerr
    - perfsprint
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - whitespace
  disable:
    - errcheck
    - ireturn
    - unused
  settings:
    funlen:
      lines: 100
      ignore-comments: true

issues:
  fix: true

formatters:
  enable:
    - gci
    - gofmt
    - goimports
