#cloud-config

hostname: ${id}
fqdn: ${id}.internal

users:
  - default
  - name: ${username}
    uid: 2001
    gecos: "UnisonDB Service User"
    shell: /bin/bash
    groups: [sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: false
packages:
  - git
  - curl
  - bash-completion
  - jq
  - build-essential
  - liblmdb-dev
  - tar
  - apt-transport-https
  - software-properties-common
  - gnupg2


write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    permissions: '0644'
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1

  - path: /etc/systemd/journald.conf
    permissions: '0644'
    content: |
      [Journal]
      Storage=persistent
      Compress=yes
      SystemMaxUse=100M
      SystemKeepFree=10M

  - path: /etc/prometheus/prometheus.yml
    permissions: '0644'
    content: |
      global:
        scrape_interval: 30s

  - path: /etc/systemd/system/prometheus.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/opt/prometheus/data \
        --web.listen-address=":9090" \
        --web.enable-lifecycle \
        --web.enable-remote-write-receiver
      Restart=on-failure
      User=nobody

      [Install]
      WantedBy=multi-user.target

  - path: /etc/grafana/provisioning/datasources/prometheus.yaml
    permissions: '0644'
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://localhost:9090
          isDefault: true
  - path: /etc/grafana/grafana.ini
    permissions: '0644'
    content: |
      [security]
      disable_login_form = true
      allow_embedding = true

      [auth.anonymous]
      enabled = true
      org_name = unisondb
      org_role = Admin


runcmd:
  - set -x
  - timedatectl set-timezone Asia/Kolkata

  - mkdir -p /var/log/journal
  - systemd-tmpfiles --create --prefix /var/log/journal
  - systemctl restart systemd-journald

  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" > /var/log/omb-install.log 2>&1
  - sed -i 's/OSH_THEME="font"/OSH_THEME="powerline-naked"/' /root/.bashrc

  - curl -LO https://github.com/prometheus/prometheus/releases/download/v${prometheus_version}/prometheus-${prometheus_version}.linux-amd64.tar.gz
  - tar -xzf prometheus-${prometheus_version}.linux-amd64.tar.gz -C /opt
  - mv /opt/prometheus-${prometheus_version}.linux-amd64 /opt/prometheus
  - ln -sf /opt/prometheus/prometheus /usr/local/bin/prometheus
  - ln -sf /opt/prometheus/promtool /usr/local/bin/promtool
  - mkdir -p /opt/prometheus/data
  - chown -R nobody:nogroup /opt/prometheus

  - curl -fsSL https://packages.grafana.com/gpg.key | gpg --dearmor -o /usr/share/keyrings/grafana.gpg
  - echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main" | tee /etc/apt/sources.list.d/grafana.list
  - apt-get update
  - apt-get install -y grafana
  - systemctl enable grafana-server
  - systemctl start grafana-server

  - systemctl daemon-reload
  - systemctl enable prometheus
  - systemctl start prometheus
  - echo "Bootstrapped ${username} on ${id}"
