## Port of the http server
http_port = 4000
pprof_enable = true

[grpc_config]
port = 4001
# SSL/TLS certificate paths for gRPC server
cert_path = "../../certs/server.crt"
key_path = "../../certs/server.key"
ca_path = "../../certs/ca.crt"

# StorageConfig stores all tunable parameters.
[storage_config]
base_dir = "/tmp/kvalchemy/server"   # Base directory for storage
namespaces = ["default", "tenant_1", "tenant_2"]
bytes_per_sync = "1MB"
segment_size = "16MB"
arena_size = "4MB"

