## Port of the http server
http_port = 4000
pprof_enable = true

[grpc_config]
port = 4001
# SSL/TLS certificate paths for gRPC server
cert_path = "../../certs/server.crt"
key_path = "../../certs/server.key"
ca_path = "../../certs/ca.crt"

# StorageConfig stores all tunable parameters.
[storage_config]
base_dir = "/tmp/unisondb/server"   # Base directory for storage
namespaces = ["default", "tenant_1", "tenant_2", "tenant_3", "tenant_4"]
bytes_per_sync = "1MB"
segment_size = "16MB"
arena_size = "4MB"

[write_notify_config]
enabled = false
max_delay = "20ms"

[storage_config.wal_cleanup_config]
interval = "5m"
enabled = false
max_age = "1h"
min_segments = 5
max_segments = 10

[pprof_config]
enabled = true
port = 6070

[log_config]
log_level = "info"

## this is for grpc logging only
[log_config.min_level_percents]
debug = 100.0
info  = 50.0
warn  = 100.0
error = 100.0

[fuzz_config]
ops_per_namespace = 400
workers_per_namespace = 50
local_relayer_count = 1000
