## Port of the http server
http_port = 6000
pprof_enable = true

[grpc_config]
port = 6001
# SSL/TLS certificate paths for gRPC server
cert_path = "../../certs/server.crt"
key_path = "../../certs/server.key"
ca_path = "../../certs/ca.crt"

# StorageConfig stores all tunable parameters.
[storage_config]
base_dir = "/tmp/unisondb/relayer"   # Base directory for storage
namespaces = ["ad-campaign", "user-targeting-profile", "ad-vector", "audience-segments", "channel-allocation"]
bytes_per_sync = "1MB"
## segment_size config should be in sync with the upstream
## else the entire sync will fail.
segment_size = "16MB"
arena_size = "4MB"

[fuzz_config]
ops_per_namespace = 10
workers_per_namespace = 2

[storage_config.wal_cleanup_config]
interval = "5m"
enabled = true
max_age = "1h"
min_segments = 5
max_segments = 30

# Relayer Configuration
[relayer_config]

[relayer_config.relayer1]
namespaces = ["ad-campaign", "user-targeting-profile", "ad-vector", "audience-segments", "channel-allocation"]
cert_path = "../../certs/client.crt"
key_path = "../../certs/client.key"
ca_path = "../../certs/ca.crt"
upstream_address = "localhost:4001"
segment_lag_threshold = 100

[log_config]
log_level = "info"

[log_config.min_level_percents]
debug = 0.01
info = 1.0
warn = 1.0
error = 1.0

[limiter]
interval = "500ms"
burst = 20