#cloud-config

hostname: ${id}
fqdn: ${id}.internal

users:
  - default
  - name: ${username}
    uid: 2001
    gecos: "UnisonDB Client User"
    shell: /bin/bash
    groups: [sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
packages:
  - git
  - curl
  - bash-completion
  - jq
  - build-essential
  - liblmdb-dev

write_files:
  - path: /etc/unisondb/config.toml
    permissions: '0644'
    content: |
      ## Port of the http server  
      http_port = 4000  
      pprof_enable = true  
      
      [grpc_config]  
      port = 4001   
      allow_insecure = true  
      
      [storage_config]  
      base_dir = "/tmp/unisondb/server"  
      namespaces = ["default", "tenant_1", "tenant_2"]  
      bytes_per_sync = "1MB"  
      segment_size = "16MB"  
      arena_size = "4MB"
      
      [relayer_config.relayer1]
      namespaces = ["default", "tenant_1", "tenant_2"]
      upstream_address = "${central_ip}:4001"
      segment_lag_threshold = 100
      allow_insecure = true
      
      [pprof_config]  
      enabled = true  
      port = 6060  
      
      [log_config]  
      log_level = "info"  
      disable_timestamp = true
      
      [log_config.min_level_percents]  
      debug = 100.0  
      info  = 100.0  
      warn  = 100.0  
      error = 100.0  
      
      [fuzz_config]  
      ops_per_namespace = 50  
      workers_per_namespace = 10

  - path: /etc/systemd/system/unisondb.service
    permissions: '0644'
    content: |
      [Unit]
      Description=UnisonDB Server
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/unisondb --config /etc/unisondb/config.toml relayer
      WorkingDirectory=/opt/unisondb
      Restart=on-failure
      User=${username}
      LimitNOFILE=65535
      StandardOutput=journal
      StandardError=journal
      SyslogIdentifier=unisondb

      [Install]
      WantedBy=multi-user.target

  - path: /etc/sysctl.d/99-tailscale.conf
    permissions: '0644'
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1

  - path: /etc/systemd/journald.conf
    permissions: '0644'
    content: |
      [Journal]
      Storage=persistent
      Compress=yes
      SystemMaxUse=100M
      SystemKeepFree=10M

  - path: /etc/prometheus/prometheus.yml
    permissions: '0644'
    content: |
      global:
        scrape_interval: 30s
        external_labels:
          instance: "${id}"

      scrape_configs:
        - job_name: "unisondb"
          static_configs:
            - targets: ["localhost:4000"]
              labels:
                instance: "${id}"
                role: "${role}"

      remote_write:
        - url: "https://api.openobserve.ai/api/${ob_token}/prometheus/api/v1/write"
          basic_auth:
            username: "${ob_user}"
            password: "${ob_pass}"

  - path: /etc/systemd/system/prometheus.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/opt/prometheus/data \
        --web.listen-address=":9090"
      Restart=on-failure
      User=nobody

      [Install]
      WantedBy=multi-user.target

runcmd:
  - set -x
  - timedatectl set-timezone Asia/Kolkata

  - mkdir -p /var/log/journal
  - systemd-tmpfiles --create --prefix /var/log/journal
  - systemctl restart systemd-journald

  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" > /var/log/omb-install.log 2>&1
  - sed -i 's/OSH_THEME="font"/OSH_THEME="powerline-naked"/' /root/.bashrc

  #- curl -fsSL https://tailscale.com/install.sh | sh
  #- sysctl -p /etc/sysctl.d/99-tailscale.conf
  #- tailscale up --hostname=${id} --authkey=${ts_auth_key}

  - wget -q https://go.dev/dl/go${go_version}.linux-amd64.tar.gz
  - rm -rf /usr/local/go && tar -C /usr/local -xzf go${go_version}.linux-amd64.tar.gz
  - echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile.d/go.sh

  - mkdir -p /opt/go /opt/go/cache
  - echo 'export PATH=$PATH:/usr/local/go/bin:/opt/go/bin' | tee /etc/profile.d/go.sh /root/.profile > /dev/null
  - echo 'export GOPATH=/opt/go' | tee -a /etc/profile.d/go.sh /root/.profile > /dev/null
  - echo 'export GOCACHE=/opt/go/cache' | tee -a /etc/profile.d/go.sh /root/.profile > /dev/null
  - chmod +x /etc/profile.d/go.sh

  - curl -LO https://github.com/prometheus/prometheus/releases/download/v${prometheus_version}/prometheus-${prometheus_version}.linux-amd64.tar.gz
  - tar -xzf prometheus-${prometheus_version}.linux-amd64.tar.gz -C /opt
  - mv /opt/prometheus-${prometheus_version}.linux-amd64 /opt/prometheus
  - ln -sf /opt/prometheus/prometheus /usr/local/bin/prometheus
  - ln -sf /opt/prometheus/promtool /usr/local/bin/promtool
  - mkdir -p /opt/prometheus/data
  - chown -R nobody:nogroup /opt/prometheus
  - systemctl daemon-reload
  - systemctl enable prometheus
  - systemctl start prometheus

  - export PATH=$PATH:/usr/local/go/bin:/opt/go/bin
  - export GOPATH=/opt/go
  - export GOCACHE=/opt/go/cache
  - git clone https://github.com/ankur-anand/unisondb.git /opt/unisondb
  - cd /opt/unisondb/cmd/unisondb && go build -tags fuzz -o /usr/local/bin/unisondb
  - chown ${username}:${username} /usr/local/bin/unisondb

  - systemctl daemon-reload
  - systemctl enable unisondb
  - systemctl start unisondb
  - echo "Bootstrapped ${username} on ${id}"
