// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package logrecord

import "strconv"

type LogOperationData byte

const (
	LogOperationDataNONE                 LogOperationData = 0
	LogOperationDataKeyValueBatchEntries LogOperationData = 1
	LogOperationDataRowUpdateEntries     LogOperationData = 2
)

var EnumNamesLogOperationData = map[LogOperationData]string{
	LogOperationDataNONE:                 "NONE",
	LogOperationDataKeyValueBatchEntries: "KeyValueBatchEntries",
	LogOperationDataRowUpdateEntries:     "RowUpdateEntries",
}

var EnumValuesLogOperationData = map[string]LogOperationData{
	"NONE":                 LogOperationDataNONE,
	"KeyValueBatchEntries": LogOperationDataKeyValueBatchEntries,
	"RowUpdateEntries":     LogOperationDataRowUpdateEntries,
}

func (v LogOperationData) String() string {
	if s, ok := EnumNamesLogOperationData[v]; ok {
		return s
	}
	return "LogOperationData(" + strconv.FormatInt(int64(v), 10) + ")"
}
