// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package walrecord

import "strconv"

type LogOperation byte

const (
	LogOperationNoop      LogOperation = 0
	LogOperationInsert    LogOperation = 1
	LogOperationDelete    LogOperation = 2
	LogOperationTxnMarker LogOperation = 3
	LogOperationDeleteRow LogOperation = 4
)

var EnumNamesLogOperation = map[LogOperation]string{
	LogOperationNoop:      "Noop",
	LogOperationInsert:    "Insert",
	LogOperationDelete:    "Delete",
	LogOperationTxnMarker: "TxnMarker",
	LogOperationDeleteRow: "DeleteRow",
}

var EnumValuesLogOperation = map[string]LogOperation{
	"Noop":      LogOperationNoop,
	"Insert":    LogOperationInsert,
	"Delete":    LogOperationDelete,
	"TxnMarker": LogOperationTxnMarker,
	"DeleteRow": LogOperationDeleteRow,
}

func (v LogOperation) String() string {
	if s, ok := EnumNamesLogOperation[v]; ok {
		return s
	}
	return "LogOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
