// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wrecord

import "strconv"

type LogOperation byte

const (
	LogOperationOpNoop        LogOperation = 0
	LogOperationOpInsert      LogOperation = 1
	LogOperationOpDelete      LogOperation = 2
	LogOperationOpBatchStart  LogOperation = 3
	LogOperationOpBatchCommit LogOperation = 4
)

var EnumNamesLogOperation = map[LogOperation]string{
	LogOperationOpNoop:        "OpNoop",
	LogOperationOpInsert:      "OpInsert",
	LogOperationOpDelete:      "OpDelete",
	LogOperationOpBatchStart:  "OpBatchStart",
	LogOperationOpBatchCommit: "OpBatchCommit",
}

var EnumValuesLogOperation = map[string]LogOperation{
	"OpNoop":        LogOperationOpNoop,
	"OpInsert":      LogOperationOpInsert,
	"OpDelete":      LogOperationOpDelete,
	"OpBatchStart":  LogOperationOpBatchStart,
	"OpBatchCommit": LogOperationOpBatchCommit,
}

func (v LogOperation) String() string {
	if s, ok := EnumNamesLogOperation[v]; ok {
		return s
	}
	return "LogOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
