// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package logrecord

import "strconv"

type EventOperation byte

const (
	EventOperationUnknown EventOperation = 0
	EventOperationInsert  EventOperation = 1
	EventOperationUpdate  EventOperation = 2
	EventOperationDelete  EventOperation = 3
)

var EnumNamesEventOperation = map[EventOperation]string{
	EventOperationUnknown: "Unknown",
	EventOperationInsert:  "Insert",
	EventOperationUpdate:  "Update",
	EventOperationDelete:  "Delete",
}

var EnumValuesEventOperation = map[string]EventOperation{
	"Unknown": EventOperationUnknown,
	"Insert":  EventOperationInsert,
	"Update":  EventOperationUpdate,
	"Delete":  EventOperationDelete,
}

func (v EventOperation) String() string {
	if s, ok := EnumNamesEventOperation[v]; ok {
		return s
	}
	return "EventOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
