// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package logrecord

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EventEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsEventEntry(buf []byte, offset flatbuffers.UOffsetT) *EventEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EventEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishEventEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEventEntry(buf []byte, offset flatbuffers.UOffsetT) *EventEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EventEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEventEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EventEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EventEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EventEntry) Pipeline() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EventEntry) SchemaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EventEntry) EventId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EventEntry) Operation() EventOperation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return EventOperation(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EventEntry) MutateOperation(n EventOperation) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *EventEntry) OccurredAt() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEntry) MutateOccurredAt(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *EventEntry) PartitionValues(obj *ColumnData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EventEntry) PartitionValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *EventEntry) Fields(obj *ColumnData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EventEntry) FieldsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EventEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func EventEntryAddPipeline(builder *flatbuffers.Builder, pipeline flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pipeline), 0)
}
func EventEntryAddSchemaId(builder *flatbuffers.Builder, schemaId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(schemaId), 0)
}
func EventEntryAddEventId(builder *flatbuffers.Builder, eventId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(eventId), 0)
}
func EventEntryAddOperation(builder *flatbuffers.Builder, operation EventOperation) {
	builder.PrependByteSlot(3, byte(operation), 0)
}
func EventEntryAddOccurredAt(builder *flatbuffers.Builder, occurredAt uint64) {
	builder.PrependUint64Slot(4, occurredAt, 0)
}
func EventEntryAddPartitionValues(builder *flatbuffers.Builder, partitionValues flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(partitionValues), 0)
}
func EventEntryStartPartitionValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EventEntryAddFields(builder *flatbuffers.Builder, fields flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(fields), 0)
}
func EventEntryStartFieldsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EventEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
