// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package logrecord

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RowUpdateEnties struct {
	_tab flatbuffers.Table
}

func GetRootAsRowUpdateEnties(buf []byte, offset flatbuffers.UOffsetT) *RowUpdateEnties {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RowUpdateEnties{}
	x.Init(buf, n+offset)
	return x
}

func FinishRowUpdateEntiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRowUpdateEnties(buf []byte, offset flatbuffers.UOffsetT) *RowUpdateEnties {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RowUpdateEnties{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRowUpdateEntiesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RowUpdateEnties) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RowUpdateEnties) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RowUpdateEnties) Entries(obj *RowUpdateEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RowUpdateEnties) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RowUpdateEntiesStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RowUpdateEntiesAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func RowUpdateEntiesStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RowUpdateEntiesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
